Added GitHub Actions
release-engineering/alt-src pull request #47
Opened 2021-08-02 17:22 UTC by daminijain23

Added -
release.yml
tox-test.yml

Deleted - 
.travis.yml

2021-09-17 19:17 UTC, rajulkumar requested changes
As suggested in other review, can the commits be squashed and a descriptive commit message be added.
Also, you may update the tox.ini and retire travis specific job in this or another commit.

2021-09-17 19:17 UTC, rajulkumar commented on .github/workflows/tox-test.yml
> +jobs:
This should also include a Py27 job.

2021-09-18 03:30 UTC, daminijain23 commented
@rajulkumar 
1. Added py27 job
2. As suggested in other repo review - removed codecov token  from tox-test.ymland change pypi_password to pypi token in release.yml.
3. squashed commit.
4. Removed travis related jobs in the same commit.

2021-09-20 03:37 UTC, rohanpm approved these changes

2021-09-20 03:37 UTC, rohanpm commented on .github/workflows/tox-test.yml
> +          sudo apt-get install -y rpm
Minor - these could all be a single command. It would be slightly more efficient.

2021-09-20 04:11 UTC, rajulkumar requested changes
[tox]
envlist = py27, py36

py36 should be changed to py38 as that's what is running in actions to avoid inconsistency. Else might introduce some confusion with tox running fine as it's using py36 but the CI running on py38 might have some errors.

2021-09-20 13:49 UTC, rajulkumar approved these changes

2021-09-21 04:47 UTC, merged